---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tlvwhzhv/public_html/games/connect-static
    - /bin/cp index.html $DEPLOYPATH
#   - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
#   - /bin/cp -R img $DEPLOYPATH